version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - docker pull $ECR_REPO_URL:builder || true
      - docker pull $ECR_REPO_URL:latest || true
  build:
    commands:
      - docker build -t $ECR_REPO_URL:builder --target builder --cache-from $ECR_REPO_URL:builder .
      - docker cp $(docker create $ECR_REPO_URL:builder):/usr/app/target/surefire-reports surefire-reports
      - if grep -q "<failure" surefire-reports/*.xml; then
          exit 1;
        else
          docker build -t $ECR_REPO_URL:latest -t $ECR_REPO_URL:$CODEBUILD_BUILD_NUMBER --cache-from $ECR_REPO_URL:builder --cache-from $ECR_REPO_URL:latest . ;
        fi
  post_build:
    commands:
      - docker push $ECR_REPO_URL:builder
      - if grep -q "<failure" surefire-reports/*.xml; then
          echo "Failed tests"
        else
          docker push $ECR_REPO_URL:latest;
          docker push $ECR_REPO_URL:$CODEBUILD_BUILD_NUMBER;
          echo "$CODEBUILD_BUILD_NUMBER" > image_tag.txt;
        fi
artifacts:
  files:
    - image_tag.txt

reports:
  junit:
    files:
      - surefire-reports/*.xml

