
version: 0.2
phases:
  install:
    commands:
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl
      - chmod +x ./kubectl && mv -f ./kubectl /usr/local/bin/kubectl
      - wget https://get.helm.sh/helm-v3.16.1-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz
      - chmod +x ./linux-amd64/helm && mv ./linux-amd64/helm /usr/local/bin/helm
      - helm plugin install https://github.com/databus23/helm-diff
  pre_build:
    commands:
      - echo "Assuming role $DEPLOYER_ROLE_ARN"
      - >
        sts=$(aws sts assume-role 
        --role-arn "$DEPLOYER_ROLE_ARN" 
        --role-session-name "test" 
        --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' 
        --output text)
      - sts=($sts)
      - aws configure set aws_access_key_id ${sts[0]}
      - aws configure set aws_secret_access_key ${sts[1]}
      - aws configure set aws_session_token ${sts[2]}
      - aws eks --region eu-central-1 update-kubeconfig --name $EKS_CLUSTER
  build:
    commands:
      - helm diff upgrade --namespace obi-ns obi k8s -f k8s/values.yaml -f k8s/values-$ENVIRONMENT.yaml --no-color --allow-unreleased