
version: 0.2
phases:
  install:
    commands:
      - if [ ! -f /usr/local/bin/terraform ]; then
          echo "Downloading Terraform...";
          wget https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip;
          unzip terraform_1.9.4_linux_amd64.zip;
        mv terraform /usr/local/bin/;
          rm terraform_1.9.4_linux_amd64.zip;
        else
          echo "Terraform binary found in cache.";
        fi

  pre_build:
    commands:
      - echo "Assuming role $WORKLOAD_ROLE_ARN"
      - >
        sts=$(aws sts assume-role 
        --role-arn "$WORKLOAD_ROLE_ARN" 
        --role-session-name "test" 
        --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' 
        --output text)
      - sts=($sts)
      - aws configure set aws_access_key_id ${sts[0]}
      - aws configure set aws_secret_access_key ${sts[1]}
      - aws configure set aws_session_token ${sts[2]}

      - terraform init -backend-config="bucket=$TF_STATE_BUCKET" -backend-config="key=$TF_STATE_KEY" -backend-config="dynamodb_table=$TF_DYNAMODB_TABLE"

  build:
    commands:
      - terraform apply -auto-approve ../01/tfplan

cache:
  paths:
    - '/usr/local/bin/terraform'
    - '/root/.terraform/**/*'
    - 'terraform.tfstate.d/**/*'